<?php

/**
 *  Change layout of page to have no wrappers when on EFQ call
 *
 */
function efq_theme_suggestions_page_alter(array &$suggestions, array $variables) {
	
	if(strpos(\Drupal::service('path.current')->getPath(), 'efq') !== false){
		$suggestions[] = 'page__ajax';
	}
	
}



/**
 *  Change layout of html to have no wrappers when on EFQ call
 *
 */
function efq_theme_suggestions_html_alter(array &$suggestions, array $variables) {
        
	if(strpos(\Drupal::service('path.current')->getPath(), 'efq') !== false){
		$suggestions[] = 'html__ajax';
	}
        
}


/** Implements hook_query_TAG_alter()
 *
 * @param \Drupal\Core\Database\Query\SelectInterface $query
 */
function efq_query_random_order_alter(Drupal\Core\Database\Query\AlterableInterface $query) {
    // Select a random element.
    $query->orderRandom();
}